AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template lanunches an EC2 with a security group that enables SSH connection.
  
Resources:
  HALİLEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02e136e904f3da870 
      InstanceType: t2.micro
      KeyName: firstkey # please use your own key
      SecurityGroups:
        - aa.second_sec_group
      Tags:
        - Key: Name
          Value: static-web
        - Key: Department
          Value: HR
      UserData:
         Fn::Base64:
            !Sub |
              #!/bin/bash
              sudo yum update - y
              sudo yum install git -y
              sudo yum install httpd -y
              cd /var/www/html/
              wget

